# Value Based Q-Learning 

## Import Python Libraries

In [1]:
import numpy as np
import gym
import time

lr = 0.1
gamma = 0.8
epsilon = 0.1
episodes = 50000

env = gym.make('Taxi-v3')

/Users/alfred/opt/anaconda3/envs/py37/lib/python3.7/site-packages/ale_py/roms/utils.py:90: DeprecationWarning: SelectableGroups dict interface is deprecated. Use select.
  for external in metadata.entry_points().get(self.group, []):


## Initialize Q Table

In [2]:
Q = np.zeros((env.observation_space.n, env.action_space.n))
print(Q)

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 ...
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


## Before Q-learning

In [3]:
s = env.reset()
done = False
step_count = 0
total_reward = 0

while not done:
    env.render()
    a = np.argmax(Q[s,:])
    s_, r, done, _ = env.step(a)
    s = s_
    step_count += 1
    total_reward += r
    time.sleep(0.1)

print("Total steps: ",step_count)
print("Total rewards: ",total_reward)

+---------+
|R: | : :G|
| : | : : |
| : : : : |
| | : | : |
|Y| : |B: |
+---------+

+---------+
|R: | : :G|
| : | : : |
| : : : : |
| | : | : |
|Y| : |B: |
+---------+
  (South)
+---------+
|R: | : :G|
| : | : : |
| : : : : |
| | : | : |
|Y| : |B: |
+---------+
  (South)
+---------+
|R: | : :G|
| : | : : |
| : : : : |
| | : | : |
|Y| : |B: |
+---------+
  (South)
+---------+
|R: | : :G|
| : | : : |
| : : : : |
| | : | : |
|Y| : |B: |
+---------+
  (South)
+---------+
|R: | : :G|
| : | : : |
| : : : : |
| | : | : |
|Y| : |B: |
+---------+
  (South)
+---------+
|R: | : :G|
| : | : : |
| : : : : |
| | : | : |
|Y| : |B: |
+---------+
  (South)
+---------+
|R: | : :G|
| : | : : |
| : : : : |
| | : | : |
|Y| : |B: |
+---------+
  (South)
+---------+
|R: | : :G|
| : | : : |
| : : : : |
| | : | : |
|Y| : |B: |
+---------+
  (South)
+---------+
|R: | : :G|
| : | : : |
| : : : : |
| | : | : |
|Y| : |B: |
+---------+
  (South)
+---------+
|R: | : :G|
| : | : : |
| : : : : |
| | : | : |
|Y| : |B:

## Q-Learning

In [4]:

for i in range(episodes):
    if i%2000 == 0: print("Episode {}/{}".format(i + 1, episodes))
    s = env.reset()
    done = False

    while not done:
        if np.random.random() < epsilon:
            a = env.action_space.sample()
        else:
            a = np.argmax(Q[s,:])
        s_, r, done, _ = env.step(a)
        Q[s,a] += lr*(r+gamma*np.max(Q[s_,:]) - Q[s,a])
        s = s_

Episode 1/50000
Episode 2001/50000
Episode 4001/50000
Episode 6001/50000
Episode 8001/50000
Episode 10001/50000
Episode 12001/50000
Episode 14001/50000
Episode 16001/50000
Episode 18001/50000
Episode 20001/50000
Episode 22001/50000
Episode 24001/50000
Episode 26001/50000
Episode 28001/50000
Episode 30001/50000
Episode 32001/50000
Episode 34001/50000
Episode 36001/50000
Episode 38001/50000
Episode 40001/50000
Episode 42001/50000
Episode 44001/50000
Episode 46001/50000
Episode 48001/50000


In [5]:
# Print Final Q Table
print(Q)

[[  0.           0.           0.           0.           0.
    0.        ]
 [ -2.85254048  -2.31587746  -2.85342715  -2.31576524  -1.6445568
  -11.31518445]
 [  0.24265502   1.55183816   0.24246627   1.55067581   3.192
   -7.44518431]
 ...
 [ -0.8775606    5.23903454   0.6246661   -0.36259966  -3.05948716
   -1.98      ]
 [ -2.45365541  -0.8072764   -2.3655792   -2.29900675  -3.80797323
   -6.24689671]
 [  4.99755669   2.89056855   3.65294317  15.           0.44377686
    0.22480968]]


## After Q-learning

In [6]:
s = env.reset()
done = False
step_count = 0
total_reward = 0

while not done:
    env.render()
    a = np.argmax(Q[s,:])
    s_, r, done, _ = env.step(a)
    s = s_
    step_count += 11
    total_reward += r
    time.sleep(0.1)

print("Total steps: ",step_count)
print("Total rewards: ",total_reward)

+---------+
|R: | : :G|
| : | : : |
| : : : : |
| | : | : |
|Y| : |B: |
+---------+

+---------+
|R: | : :G|
| : | : : |
| : : : : |
| | : | : |
|Y| : |B: |
+---------+
  (West)
+---------+
|R: | : :G|
| : | : : |
| : : : : |
| | : | : |
|Y| : |B: |
+---------+
  (Pickup)
+---------+
|R: | : :G|
|_: | : : |
| : : : : |
| | : | : |
|Y| : |B: |
+---------+
  (South)
+---------+
|R: | : :G|
| : | : : |
|_: : : : |
| | : | : |
|Y| : |B: |
+---------+
  (South)
+---------+
|R: | : :G|
| : | : : |
| : : : : |
|_| : | : |
|Y| : |B: |
+---------+
  (South)
+---------+
|R: | : :G|
| : | : : |
| : : : : |
| | : | : |
|Y| : |B: |
+---------+
  (South)
Total steps:  7
Total rewards:  14
