# Value-Based SARSA Reinforcement Learning

## Import Python Libraries

In [1]:
fifiimport numpy as np
import gym
import time

#env = gym.make('FrozenLake-v0')
env = gym.make("Taxi-v3").env

/Users/alfred/opt/anaconda3/envs/py37/lib/python3.7/site-packages/ale_py/roms/utils.py:90: DeprecationWarning: SelectableGroups dict interface is deprecated. Use select.
  for external in metadata.entry_points().get(self.group, []):


In [2]:
## Initialize Q Table
Q = np.zeros((env.observation_space.n, env.action_space.n))
print(Q)

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 ...
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [3]:
## Before SARSA Learning

s = env.reset()
done = False
step_count = 0
total_reward = 0

while not done:
    env.render()
    a = np.argmax(Q[s,:])
    s_, r, done, _ = env.step(a)
    s = s_
    step_count += 1
    total_reward += r
    time.sleep(0.1)
    if step_count > 200: break

print("Total steps: ",step_count)
print("Total rewards: ",total_reward)

+---------+
|R: | : :G|
| : | : : |
| : : : : |
| | : | : |
|Y| : |B: |
+---------+

+---------+
|R: | : :G|
| : | : : |
| : : : : |
| | : | : |
|Y| : |B: |
+---------+
  (South)
+---------+
|R: | : :G|
| : | : : |
| : : : : |
| | : | : |
|Y| : |B: |
+---------+
  (South)
+---------+
|R: | : :G|
| : | : : |
| : : : : |
| | : | : |
|Y| : |B: |
+---------+
  (South)
+---------+
|R: | : :G|
| : | : : |
| : : : : |
| | : | : |
|Y| : |B: |
+---------+
  (South)
+---------+
|R: | : :G|
| : | : : |
| : : : : |
| | : | : |
|Y| : |B: |
+---------+
  (South)
+---------+
|R: | : :G|
| : | : : |
| : : : : |
| | : | : |
|Y| : |B: |
+---------+
  (South)
+---------+
|R: | : :G|
| : | : : |
| : : : : |
| | : | : |
|Y| : |B: |
+---------+
  (South)
+---------+
|R: | : :G|
| : | : : |
| : : : : |
| | : | : |
|Y| : |B: |
+---------+
  (South)
+---------+
|R: | : :G|
| : | : : |
| : : : : |
| | : | : |
|Y| : |B: |
+---------+
  (South)
+---------+
|R: | : :G|
| : | : : |
| : : : : |
| | : | : |
|Y| : |B:

In [4]:
## Action Policy

def choose_action(s, Q):
    if np.random.random() < epsilon:
        a = np.random.randint(0, env.action_space.n)
    else:
        a = np.argmax(Q[s,:])
    return a

In [5]:
## SARSA

lr = 0.05
gamma = 0.9
epsilon = 0.1
episodes = 50000

for i in range(episodes):
    if i%2000 == 0: print("Episode {}/{}".format(i + 1, episodes))
    s = env.reset()
    done = False
        
    a = choose_action(s, Q)
    while not done:
        s_, r, done, _ = env.step(a)
        a_ = choose_action(s_, Q)
        Q[s,a] = Q[s,a] + lr*(r+gamma*(Q[s_,a_]) - Q[s,a])
        s = s_
        a = a_

Episode 1/50000
Episode 2001/50000
Episode 4001/50000
Episode 6001/50000
Episode 8001/50000
Episode 10001/50000
Episode 12001/50000
Episode 14001/50000
Episode 16001/50000
Episode 18001/50000
Episode 20001/50000
Episode 22001/50000
Episode 24001/50000
Episode 26001/50000
Episode 28001/50000
Episode 30001/50000
Episode 32001/50000
Episode 34001/50000
Episode 36001/50000
Episode 38001/50000
Episode 40001/50000
Episode 42001/50000
Episode 44001/50000
Episode 46001/50000
Episode 48001/50000


In [6]:
# Print Final Q Table
print(Q)

[[  0.           0.           0.           0.           0.
    0.        ]
 [ -3.19445651  -2.0985767   -3.40912437  -2.1022281   -1.52611213
  -11.19191563]
 [  1.85759155   3.72809167   1.7693007    3.73987409   5.77888218
   -5.10260312]
 ...
 [ -0.84853369   6.97645318  -0.83753946  -0.5711082   -1.90910665
   -1.68071833]
 [ -2.56548458  -2.610708    -2.53369047  -0.14764225  -4.36893406
   -3.20697495]
 [  2.48112281   1.77878125  -0.0975      16.61518548   0.52362161
   -0.13072272]]


In [7]:
## After SARSA Learning

s = env.reset()
done = False
step_count = 0
total_reward = 0

while not done:
    env.render()
    a = np.argmax(Q[s,:])
    s_, r, done, _ = env.step(a)
    s = s_
    step_count += 1
    total_reward += r
    time.sleep(0.1)
    if step_count > 200: break

print("Total steps: ",step_count)
print("Total rewards: ",total_reward)

+---------+
|R: | : :G|
| : | : : |
| : : : : |
| | : | : |
|Y| : |B: |
+---------+

+---------+
|R: | : :G|
| : | : : |
| : : : : |
| | : | : |
|Y| : |B: |
+---------+
  (North)
+---------+
|R: | : :G|
| : | : : |
| : : : : |
| | : | : |
|Y| : |B: |
+---------+
  (North)
+---------+
|R: | : :G|
| : | : : |
| : : : : |
| | : | : |
|Y| : |B: |
+---------+
  (North)
+---------+
|R: | : :G|
| : | : : |
| : : : : |
| | : | : |
|Y| : |B: |
+---------+
  (North)
+---------+
|R: | : :G|
| : | : : |
| : : : : |
| | : | : |
|Y| : |B: |
+---------+
  (Pickup)
+---------+
|R:_| : :G|
| : | : : |
| : : : : |
| | : | : |
|Y| : |B: |
+---------+
  (East)
+---------+
|R: | : :G|
| :_| : : |
| : : : : |
| | : | : |
|Y| : |B: |
+---------+
  (South)
+---------+
|R: | : :G|
| : | : : |
| :_: : : |
| | : | : |
|Y| : |B: |
+---------+
  (South)
+---------+
|R: | : :G|
| : | : : |
| : :_: : |
| | : | : |
|Y| : |B: |
+---------+
  (East)
+---------+
|R: | : :G|
| : | : : |
| : : :_: |
| | : | : |
|Y| : |B: 

In [ ]:
import numpy as np
import gym
import time

#env = gym.make('FrozenLake-v0')
env = gym.make("Taxi-v3").env